### ISSUE TITLE
Unable to load environment variables from .env file

### ISSUE THREAD

**Issue by peavers** [sjmayotte/route53-dynamic-dns#10]
Everything was cool until I pulled the latest update. Now when attempting to start the container I just get:

```
[2021-02-18T15:53:05.144] [INFO] default - Unable to load environment variables from .env file.  Process is likely running in a container.  Make sure you pass environment variables when starting container.
[2021-02-18T15:53:05.145] [ERROR] default - Error: ENOENT: no such file or directory, open '/usr/src/app/.env'
    at Object.openSync (fs.js:440:3)
    at Object.readFileSync (fs.js:342:35)
    at Object.config (/usr/src/app/node_modules/dotenv/lib/main.js:96:29)
    at Object.<anonymous> (/usr/src/app/server.js:59:29)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11 {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/usr/src/app/.env'
}
```

I'm starting via a docker-compose script

```
  route53-dynamic-dns:
    container_name: route53-dynamic-dns
    image: sjmayotte/route53-dynamic-dns:latest
    restart: unless-stopped
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - ROUTE53_HOSTED_ZONE_ID=${ROUTE53_HOSTED_ZONE_ID}
      - ROUTE53_DOMAIN=${DOMAIN}
      - ROUTE53_TYPE=A
      - ROUTE53_TTL=60
      - SEND_EMAIL_SES=false
      - SES_TO_ADDRESS=${SES_TO_ADDRESS}
      - SES_FROM_ADDRESS=${SES_FROM_ADDRESS}
      - UPDATE_FREQUENCY=60000
      - LOG_TO_STDOUT=true
    logging:
      options:
        max-size: "2m"
        max-file: "5"
    labels:
      - traefik.enable=false
```
